### ISSUE TITLE
Magento 2.3 update

### ISSUE THREAD

**Issue by dimdimich** [swissup/absolute-metapackage#1]
Are you going to patch thiss to work with 2.3. updator is no longer used by Magento. This however is a requirement in the module? poor implementation

**Comment by Yosuatel** [comment]
I'm very stuck in in shh. You can tell me how to remove or uninstall this module and what commands to use, it does not let me update magento 2 to the latest version. I appreciate it so much.
a greeting

**Comment by vovayatsyuk** [comment]
Hi, 

What message do you receive when trying to update Magento?

**Comment by Yosuatel** [comment]
The version magento2 that I use is 2.2.5

Check Component Dependency
We found conflicting component dependencies. Hide detail

Command "update" failed: Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- swissup/slick-carousel 1.1.0 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.22) does not satisfy that requirement.
- swissup/slick-carousel 1.1.0 requires php ~5.5.0|~5.6.0|~7.0.0 -> your PHP version (7.1.22) does not satisfy that requirement.
- swissup/absolute-metapackage 1.1.2 requires swissup/slick-carousel 1.1.0 -> satisfiable by swissup/slick-carousel[1.1.0].
- Installation request for swissup/absolute-metapackage 1.1.2 -> satisfiable by swissup/absolute-metapackage[1.1.2].

thanks for your support

**Comment by vovayatsyuk** [comment]
Try again. I've updated theme dependencies and it will no longer require old PHP version.

**Comment by vovayatsyuk** [comment]
Hi,

Did you resolve this issue?
