### ISSUE TITLE
Problem with installation on Marketplace

### ISSUE THREAD

**Issue by dimdimich** [swissup/absolute-metapackage#3]
https://marketplace.magento.com/catalog/product/view/id/1223/s/swissup-absolute-metapackage/#product.info.details.release_notes 

I've tried to install Absolute Theme, but the Readiness Check found a conflicting issue. > Command ""require"" failed: > In InitCommand.php line 730: > Package has a PHP requirement incompatible with your PHP version (7.3.16).

Do we have any top PHP requirements set in composer.json for any package?

**Comment by vovayatsyuk** [comment]
No, they were removed in 1.1.1.
